### ISSUE TITLE
tests: 

### ISSUE THREAD

**Issue by alex-nexus** [tebayoso/ipsymusic#6]
I notice you wrote good tests for requests and acceptance. is there any reason that there is no test for controllers and models?

**Comment by tebayoso** [comment]
There's a thin line in testing between ensuring code quality and improve code development, and swamping developers in the hell of test maintenance. I believe code should be tested based on some criteria:
1)Is it something that's not tested elsewhere?
In this application all the code is tested either in the gems used (like the swagger documentation gem) or in the rails core app (like the validations, and associations helpers)
Ensuring that the rails validation method works, forces developers to rewrite tests over and over:
```
class Model < ApplicationRecord
    validates :attributes, with: ActiveModel::Validations
end

describe 'when testing a method that is built-in rails' do
   context 'we should ensure that it works and' do
       it 'it should be double tested' do
            model = Model.new(:some_invalid_params)
            expect(model.valid?).to be(false)
        end
   end
end
```
Is a waste of time, we didn't write this validator, and it's already tested in the Rails core.
BUT!
```
class MyValidator < ActiveModel::Validator
  def validate(record)
    unless record.name.starts_with? 'X'
      record.errors[:name] << 'Need a name starting with X please!'
    end
  end
end
 
class Model
  include ActiveModel::Validations
  validates_with MyValidator
end

describe 'when testing a method that validated with OUR CUSTOM VALIDATOR' do
   context 'we should ensure that it works and' do
       it 'it should tested' do
            model = Model.new(:some_invalid_params)
            expect(model.valid?).to be(false)
        end
   end
end
```

We can debate about this, but I like this  `good practice`
